name: 'Build'
description: 'Build the branch'
runs:
  using: "composite"
  steps:
    - name: Build
      shell: bash
      run: |
          echo "node version"
          node -v
          git status
          npm run build --if-present
          echo "Build Finished"