name: 'Build'
description: 'Build the branch'
inputs:
  userName:
    description: 'git config user.name'
    default: 'Barry Mittens'
  userEmail:
    description: 'git config user.email'
    default: 'someone@test.com'
  target:
    description: 'Branch that needs to be built'
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup git
      shell: bash
      run: |
          git config --local user.email "${{ inputs.userEmail }}"
          git config --local user.name "${{ inputs.userName }}"
    - name: Build
      uses: actions/setup-node@v2
        with:
          node-version: '12'
        run: |
          npm install
          npm run build
          git add . && git diff --quiet && git diff --staged --quiet || git commit -am 'Automated build [skip ci]'
          git push