name: 'Build'
description: 'Build the branch'
inputs:
  userName:
    description: 'git config user.name'
    default: 'Barry Mittens'
  userEmail:
    description: 'git config user.email'
    default: 'someone@test.com'
  target:
    description: 'Branch that needs to be built'
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup git
      shell: bash
      run: |
          git config --local user.email "${{ inputs.userEmail }}"
          git config --local user.name "${{ inputs.userName }}"
    - name: Build
      shell: bash
      run: |
          echo "node version"
          node -v
          echo "Fetching all"
          git fetch --all
          echo "Doing checkout of branch ${{ inputs.target }}"
          git switch ${{ inputs.target }}
          npm install
          npm run build
          echo "Get status"
          git status
          git add . && git diff --quiet && git diff --staged --quiet || git commit -am 'Automated build [skip ci]'
          echo "Pushing to origin"
          git push origin ${{ inputs.target }} -f